### ISSUE TITLE
Get Exception to Read Asta file

### ISSUE THREAD

**Issue by raviarsuda05** [joniles/mpxj#143]
I got below error to read asta (.pp) file

`Exception in thread "main" java.lang.NoSuchMethodError: org.sqlite.JDBC.createConnection(Ljava/lang/String;Ljava/util/Properties;)Ljava/sql/Connection;
	at net.sf.mpxj.asta.AstaDatabaseFileReader.read(AstaDatabaseFileReader.java:91)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.read(AstaDatabaseFileReader.java:75)
	at com.visilean.cms.security.TestPrimavera.main(TestPrimavera.java:30)
`

**Comment by joniles** [comment]
Looks like the SQLite jar (if you are using Java) or assembly (if you are using .Net) isn't available.
