### ISSUE TITLE
Exception on reading of an MPX file that uses wk unit

### ISSUE THREAD

**Issue by arcady-zherdev** [joniles/mpxj#250]
Reading of the attached MPX-file causes an exception: 
[1.zip](https://github.com/joniles/mpxj/files/7733388/1.zip)

```
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:131)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:104)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:93)
	at bryntum.gantt.msprojectreader.Main.main(Main.java:64)
Caused by: net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:314)
	at net.sf.mpxj.reader.UniversalProjectReader.handleFile(UniversalProjectReader.java:531)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:125)
	... 3 more
Caused by: net.sf.mpxj.MPXJException: Error reading file (failed at line 129)
	at net.sf.mpxj.mpx.MPXReader.read(MPXReader.java:192)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:353)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:211)
	... 5 more
Caused by: net.sf.mpxj.MPXJException: Invalid time unit wk
	at net.sf.mpxj.mpx.TimeUnitUtility.getInstance(TimeUnitUtility.java:61)
	at net.sf.mpxj.mpx.DurationUtility.getInstance(DurationUtility.java:88)
	at net.sf.mpxj.mpx.MPXReader.populateTask(MPXReader.java:1161)
	at net.sf.mpxj.mpx.MPXReader.parseRecord(MPXReader.java:392)
	at net.sf.mpxj.mpx.MPXReader.read(MPXReader.java:167)
	... 7 more
```

The code seems doesn't like `wk` duration unit used in the file. 

Checked on version 10.0.1

**Comment by joniles** [comment]
Hello! Thanks for the report, and apologies for. the delay in responding. I've fixed the issue and the change will be available in the next release of MPXJ.
