### ISSUE TITLE
Reading from .pp File got Exception,Unsupported SQL type: 0 for column DATA_AS_NOTE

### ISSUE THREAD

**Issue by 136759790** [joniles/mpxj#434]
Hi,thank you for the awsome conponent, but when I import a .pp file,I got an exception below.
`
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.getRows(AstaDatabaseFileReader.java:235)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.processCustomFields(AstaDatabaseFileReader.java:215)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.read(AstaDatabaseFileReader.java:105)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.read(AstaDatabaseFileReader.java:85)
	at net.sf.mpxj.asta.AstaDatabaseFileReader.read(AstaDatabaseFileReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:368)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:472)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:237)
`
Follow it,I found that in the class **### SqliteResultSetRow**，and the type is 0 ,
`
 default:
            {
               throw new IllegalArgumentException("Unsupported SQL type: " + type + " for column " + name);
            }
`
How can i resolve this problem?

**Comment by joniles** [comment]
Hello, thanks for the bug report. Would you be able to attach or send me directly a PP file which I can use to reproduce the issue?

**Comment by 136759790** [comment]
Yes, ofcourse, github dose not support upload .pp file,you can download it from  [here](http://cloudt-aliyun-test-vpc-pub.oss-cn-beijing.aliyuncs.com/gsite/zhaoxt-test/a.pp).
Thanks a lot.

**Comment by 136759790** [comment]
http://cloudt-aliyun-test-vpc-pub.oss-cn-beijing.aliyuncs.com/gsite/zhaoxt-test/a.pp

**Comment by joniles** [comment]
Thanks for uploading the file. I used MPXJ 11.1.0 and was able to read the file successfully. Would you be able to try this version to see if it works for you?

**Comment by 136759790** [comment]
I have tried it,but also same.
JDK8
`
<dependency>
	<groupId>net.sf.mpxj</groupId>
	<artifactId>mpxj</artifactId>
	<version>11.1.0</version>
</dependency>
`
my test code
`
@Test
    public void importFileByMpxj() throws Exception {
    	File folder = new File("C:\\\\Users\\\\zhaoxt\\\\Documents\\\\WXWork\\\\1688854982239193\\\\Cache\\\\File\\\\2023-02\\\\propress\\\\propress\\aa\\");
    	File[] files = folder.listFiles();
    	List<String> result = new ArrayList<>();
    	Arrays.stream(files).forEach(i->{
    		System.out.println(i.getAbsolutePath()+"--->start");
    		try(FileInputStream inputStream = new FileInputStream(i)){
    			UniversalProjectReader reader = new UniversalProjectReader();
    			reader.read(inputStream);
    			result.add(i.getAbsolutePath());
    			System.out.println(i.getAbsolutePath()+"--->end");
			} catch (Exception e) {
				e.printStackTrace();
				System.out.println("parse error-->"+i.getAbsolutePath());
			}
    		
    	});
    }
`
error log
`
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\a.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\a.pp
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\b.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\b.pp
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\c.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\c.pp
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\d.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\d.pp
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\e.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\e.pp
C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\f.pp--->start
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:171)
	at com.glodon.bim5d.export.TestExport.lambda$0(TestExport.java:201)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.glodon.bim5d.export.TestExport.importFileByMpxj(TestExport.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Unsupported SQL type: 0 for column DATA_AS_NOTE
	at net.sf.mpxj.asta.SqliteResultSetRow.<init>(SqliteResultSetRow.java:144)
	at net.sf.mpxj.asta.AstaSqliteReader.getRows(AstaSqliteReader.java:235)
	at net.sf.mpxj.asta.AstaSqliteReader.processUserDefinedFields(AstaSqliteReader.java:215)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:105)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:85)
	at net.sf.mpxj.asta.AstaSqliteReader.read(AstaSqliteReader.java:59)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:425)
	at net.sf.mpxj.reader.UniversalProjectReader.handleSQLiteFile(UniversalProjectReader.java:552)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:292)
	... 29 more
parse error-->C:\Users\zhaoxt\Documents\WXWork\1688854982239193\Cache\File\2023-02\propress\propress\aa\f.pp
`

**Comment by joniles** [comment]
Hello! Thanks for the updated information.

When you are testing this, does your Maven POM have any other dependencies in it apart from MPXJ? I wondering if there might be something else using a different SQLite version.

Also... which version and distribution of Java do you have installed?

**Comment by 136759790** [comment]
Great, I did use an older version of sqlite, and the problem was fixed when I updated to the latest version,thanks a lot

**Comment by joniles** [comment]
That's great news - very pleased that's working for you now. All the best! Jon
