### ISSUE TITLE
MPXJ is unable to parse MPP file exported from Project Online

### ISSUE THREAD

**Issue by VipulADSK** [joniles/mpxj#443]
Hi @joniles ,

Hope you are doing well.

We have a file in which the MPXJ is unable to parse the file and we are getting exception as below

`Exception in thread "main" net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:370)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:189)
	at net.sf.mpxj.reader.UniversalProjectReader.readAll(UniversalProjectReader.java:178)
	at com.autodesk.acs.schedule.strategies.ExtractionStrategy.extract(ExtractionStrategy.java:39)
	at com.autodesk.acs.schedule.DebugMain.debugExtractTasks(DebugMain.java:16)
	at com.autodesk.acs.schedule.DebugMain.main(DebugMain.java:26)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.sf.mpxj.mpp.MPPUtility.getInt(MPPUtility.java:209)
	at net.sf.mpxj.mpp.VarDataFieldReader.getValue(VarDataFieldReader.java:64)
	at net.sf.mpxj.mpp.FieldMap$FieldItem.readVarData(FieldMap.java:1019)
	at net.sf.mpxj.mpp.FieldMap$FieldItem.read(FieldMap.java:766)
	at net.sf.mpxj.mpp.FieldMap.populateContainer(FieldMap.java:447)
	at net.sf.mpxj.mpp.MPP14Reader.processTaskData(MPP14Reader.java:1120)
	at net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:95)
	at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:167)
	at net.sf.mpxj.reader.UniversalProjectReader.handleOleCompoundDocument(UniversalProjectReader.java:469)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:252)`

Can you please help us to know on why this is happening and a way to resolve this? I have uploaded the file with this Issue. [Sample.mpp.zip](https://github.com/joniles/mpxj/files/10878953/Sample.mpp.zip)

**Comment by VipulADSK** [comment]
cc: @liron.zulf@autodesk.com

**Comment by joniles** [comment]
Hello! Many thanks for the bug report and the sample file. I've fixed the issue, the changes are in git and will be in the next release.
