### ISSUE TITLE
NPE when importing some XER files with calendar exceptions  

### ISSUE THREAD

**Issue by radimbk** [joniles/mpxj#721]
The import fails with NPE:
Caused by: java.lang.NumberFormatException: Cannot parse null string
        at java.base/java.lang.Integer.parseInt(Integer.java:623) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:777) ~[?:?]
        at net.sf.mpxj.primavera.PrimaveraReader.processCalendarExceptions(PrimaveraReader.java:660) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.primavera.PrimaveraReader.processCalendar(PrimaveraReader.java:489) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.primavera.PrimaveraReader.processCalendars(PrimaveraReader.java:414) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.primavera.PrimaveraXERFileReader.processCalendars(PrimaveraXERFileReader.java:528) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.primavera.PrimaveraXERFileReader.readProject(PrimaveraXERFileReader.java:252) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.primavera.PrimaveraXERFileReader.readAll(PrimaveraXERFileReader.java:183) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.reader.UniversalProjectReader$StreamReaderProxy.readAll(UniversalProjectReader.java:163) ~[mpxj-12.9.1.jar:?]
        at net.sf.mpxj.reader.UniversalProjectReader.readAll(UniversalProjectReader.java:336) ~[mpxj-12.9.1.jar:?]

Unfortunately cannot share the file as it contains customer data.

**Comment by joniles** [comment]
Hello! Thanks for raising the issue. First question: which version of MPXJ are you using?

**Comment by joniles** [comment]
Actually, don't worry I can see 12.9.1 in the stack trace - I should have looked closer!

**Comment by joniles** [comment]
Can you try using the latest version (13.0.2), or if that causes you issues, try the most recent 12.x release (12.10.3), and let me know how you get on?

**Comment by joniles** [comment]
Thanks for confirming that. There are a few options which would allow me to resolve this:

1. I suspect that the calendar information section of the XER file won't contain any sensitive information, so if you can open the file in a text editor and copy the lines from `%T	CALENDAR` down to the next line starting with `%T` I can work with that. Feel free to email that to me directly rather than sharing publicly here (jon@timephased.com is the best address).
2. I'm happy to sign an NDA so you can share the file with me privately, again email me at jon@timephased.com to start the ball rolling.
3. There is a tool shipped with MPXJ which will allow you to "anonymise" a schedule file so that it is safe to be shared. Might be worth giving that a try, the details are here: https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/utility/ProjectCleanUtility.java again you can email me the results when you have them.

**Comment by radimbk** [comment]
Just sent you a separate email to the address you provided with the calendar excerpt (1 from above)

**Comment by joniles** [comment]
The code to fix this issue has been merged and will be available as part of the next MPXJ release.
