### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException when reading an MPP file

### ISSUE THREAD

**Issue by kirlev** [joniles/mpxj#784]
Hi @joniles,

We found that when reading a specific MPP file we receive the following error:
````
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.sf.mpxj.reader.UniversalProjectReader.readAll(UniversalProjectReader.java:347)
	at com.autodesk.acs.schedule.strategies.ExtractionStrategy.extract(ExtractionStrategy.java:43)
	at com.autodesk.acs.schedule.DebugMain.debugExtractTasks(DebugMain.java:16)
	at com.autodesk.acs.schedule.DebugMain.main(DebugMain.java:26)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.sf.mpxj.mpp.MPPUtility.getShort(MPPUtility.java:190)
	at net.sf.mpxj.mpp.CustomFieldValueReader.getTypedValue(CustomFieldValueReader.java:137)
	at net.sf.mpxj.mpp.CustomFieldValueReader.process(CustomFieldValueReader.java:95)
	at net.sf.mpxj.mpp.MPP14Reader.processCustomValueLists(MPP14Reader.java:231)
	at net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:97)
	at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:166)
	at net.sf.mpxj.reader.UniversalProjectReader$2.readAll(UniversalProjectReader.java:644)
	at net.sf.mpxj.reader.UniversalProjectReader.readAll(UniversalProjectReader.java:337)
````
Can you please help resolve this?

The file is attached.

[exampleFile.mpp.zip](https://github.com/user-attachments/files/18052780/exampleFile.mpp.zip)

**Comment by joniles** [comment]
Hi @kirlev can you confirm the version of MPXJ you are using? I've just tried this with the current version and the file reads ok.

**Comment by kirlev** [comment]
@joniles you are correct, I was using v12.10.3.

Thanks!
